### ISSUE TITLE
Manage Saved Networks shows nothing

### ISSUE THREAD

**Issue by tiocfaidharla** [nemomobile-ux/glacier-settings#44]
I tried to connect to my sfos hotspot and failed, after successfully using my normal wifi. Manage Saved Networks showed nothing.

**Comment by jmlich** [comment]
The problem is caused by difference between sailfishos and upstream version of connman. The libconnman-qt tries to provide interface to something what is not defined in upstream connman.

I guess problem is solved by https://github.com/nemomobile-ux/glacier-settings/commit/17a8e9ae44a45013443be28f9bf7b0cc69d921ee
